# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: inyogeshwar # Replace with a single Patreon username
ko_fi: yogeshwarkumar # Replace with a single Ko-fi username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
